# -*- coding: utf-8 -*-
"""barras e setores

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gyDtiNeXw6QFC-JGvhcYbib9dZWeNhxK

#Gráfico de barras e setores
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io

from google.colab import files
uploaded = files.upload()

Data = pd.read_csv("insect.csv") #Chamando pelo nome o arquivo: dataset
Data.head() #ler

Data.shape

agrupamento=Data.groupby(["spray"])["count"].sum()
agrupamento
#agrupamento dos dados baseado no atributo APRAY, contando e somando os registros

agrupamento.plot.bar(color="pink")
#gráfico de barras // tem legenda

agrupamento.plot.bar(color=["blue", "yellow", "red", "green", "pink", "orange"]) 
#cores

agrupamento.plot.pie()
#gráfico de pizza

agrupamento.plot.pie(legend=True) #legenda pizza



